
apiVersion: v1
kind: Service
metadata:
  name: {{ include "invoice-platform.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "invoice-platform.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "invoice-platform.fullname" . }}-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
