
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "invoice-platform.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "invoice-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "invoice-platform.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "invoice-platform.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
          env:
            - name: DB_HOST
              value: "{{ include "invoice-platform.fullname" . }}-postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "invoice-platform.fullname" . }}-db
                  key: database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "invoice-platform.fullname" . }}-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "invoice-platform.fullname" . }}-db
                  key: password
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.targetPort }}
            failureThreshold: 30
            periodSeconds: 10
          resources: {}
