
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "invoice-platform.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "invoice-platform.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "invoice-platform.fullname" . }}-postgres
  serviceName: {{ include "invoice-platform.fullname" . }}-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "invoice-platform.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "invoice-platform.fullname" . }}-db
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "invoice-platform.fullname" . }}-db
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "invoice-platform.fullname" . }}-db
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
