
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "invoice-platform.fullname" . }}-db
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
  database: {{ .Values.postgres.auth.database | quote }}
